theme: jekyll-theme-minimal
title: Taller de aplicaciones y casos de uso de ML & IA - Caja Rural de Granada
description: Aplicaciones de Location Intelligence
logo: /assets/images/logo.png
show_downloads: false
google_analytics:
