theme: jekyll-theme-minimal
title: Taller de aplicaciones y casos de uso de ML & IA
description: Aplicaciones de Location Intelligence
logo: /assets/images/logo.png
show_downloads: false
google_analytics:
